### ISSUE TITLE
last supper debug search

### ISSUE THREAD

**Issue by MagicalMatrix** [argian/artEye#75]
explore whether the mesterious errors when building project upon android are causing the last supper to do not work in quest vr
(ps. there are errors regarding automatic render queue setup)

**Comment by Kimel-PK** [comment]
During Android build there are errors with `LocalPlayer.GetTrackingData()`, possible outcomes:

- These errors are causing the last supper and the persistence of memory to do not work in vr mode
- These are errors only in editor due to VRChat entering playmode for scene publish

I cannot test it without headset, Rift S is not standalone headset and I can only launch pc version

**Comment by Kimel-PK** [comment]
It turned out that these were editor only problems which closes this issue
